name: Cypress Tests

on:
  push:
    branches:
      - main  # ajuste conforme o nome da sua branch principal
  pull_request:
    branches:
      - main  # ajuste conforme o nome da sua branch principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run mantis # ajuste para o script npm usado para rodar seus testes Cypress
